### ISSUE TITLE
Game does not work (missing file)

### ISSUE THREAD

**Issue by Efreak** [angarg12/TrueExponential#6]
Console: `GET http://angarg12.github.io/TrueExponential/js/angular.min.js.map 404 (Not Found)`

**Comment by angarg12** [comment]
Thank you for your report.

Could you please give more details about the issue?

Are you running the web version or in local?

Which version of the game?

**Comment by angarg12** [comment]
The problem is (quite obviously) that the deployment is missing the mapping map for the minified version of angular.js.

I will add it to the repo.

**Comment by angarg12** [comment]
The file has been added to the repo and the website. 

Please check and reopen if the problem persists.

**Comment by Efreak** [comment]
Fixed. I'll submit new issues for the new issues...
